/*
 * This source file was generated by the Gradle 'init' task
 */
package taller3;

public class App {

   public static void main(String[] args) {
   

   }

   /*
    * 1. Construya un algoritmo e implemente la función en Java Escribir_asc que
    * reciba tres números enteros diferentes
    * y devuelva en un String en orden ascendente con el siguiente formato:
    * "##### - ##### - #####", donde el primero es
    * el mayor de todos, el segundo el del medio, el tercero el menor de todos. Si
    * hay al menos dos números iguales,
    * devolverá el mensaje: "Error: La función no considera números iguales". Si
    * hay un error inesperado, deberá mostrar
    * el mensaje: "Ocurrió un error inesperado".
    */
public static String Escribir_asc(int nro_1, int nro_2, int nro_3){
    try {

       String orden = "";
       if(nro_1 == nro_2 || nro_1 == nro_3 || nro_2 == nro_3 ){
          return "Error: La función no considera números iguales";
       }
       else if(nro_1 > nro_2 && nro_2 > nro_3){
          orden = nro_1 + " - " + nro_2 + " - " + nro_3;
          return orden;
       }
       else if(nro_1 > nro_3 && nro_3 > nro_2){
          mensaje = nro_1 + " - " + nro_3 + " - " + nro_2;
          return mensaje;
       }
       else if(nro_2 > nro_1 && nro_1 > nro_3){
          orden = nro_2 + " - " + nro_1 + " - " + nro_3;
          return orden;
       }
       else if(nro_2 > nro_3 && nro_3 > nro_1){
          orden = nro_2 + " - " + nro_3 + " - " + nro_1;
          return orden;
       }
       else if(nro_3 > nro_2 && nro_2 > nro_1){
          orden = nro_3 + " - " + nro_2 + " - " + nro_1;
          return orden;
       }
       else if(nro_3 > nro_1 && nro_1 > nro_2){
          orden = nro_3 + " - " + nro_1 + " - " + nro_2;
          return orden;
       }
       else{
          return "Ocurrió un error inesperado";
       }
    } 
   
    catch (Exception e) {
       return "Ocurrió un error inesperado";
    }
 }


   /*
    * 2. Construya un algoritmo e implemente la función en Java Obtener_cifras que
    * recibe un número entre 0 y 50.000
    * y devuelve byte con las cifras que tiene. Por ejemplo 10 tiene dos cifras,
    * 9999 tiene 4 cifras. Si el número
    * no está en el rango devuelve 0. Y si hay un error inesperado, devuelve -1.
    * 
    */
 
   public static byte Obtener_cifras (int nro_){
   
    try {

         byte cifras = 0;

         if (nro_ < 0 || nro_ > 50000){
            return 0;
         }
         if (nro_ < 10) {
            cifras = 1;
         }else if (nro_ < 100){
            cifras = 2;
         } else if (nro_ < 100){
            cifras = 3;
         } else if (nro_ < 1000){
            cifras = 4;
         } else if (nro_ < 10000){
            cifras = 5;
         }
    } 
    catch (Exception e) {
        return -1;
    }
 }

   /*
    * 3. Construya un algoritmo e implemente la función en Java Clasificar_char que
    * recibe un caracter, y
    * devuelve un string de acuerdo con las siguientes condiciones: si es un
    * alfabético, deuvelve "ES LETRA";
    * si es numérico, devuelve "ES NUMERO" o si es un carácter especial, devuelve
    * "ESPECIAL".
    * Los caracteres se validan de acuerdo con la tabla ascii básica y lo explicado
    * en clase.
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */

 public static String Clasificar_char(char caracter){
          try {
              int caracter_ascii=(int)caracter;
              String mensaje= " ";

              if((caracter_ascii>=65 && caracter_ascii<=90)||(caracter_ascii>=97 && caracter_ascii<=122)){
                  mensaje= "ES LETRA";
              }
              else if(caracter_ascii>=48 && caracter_ascii<=57){
                  mensaje= "ES NUMERO";
              }else if((caracter_ascii>=33 && caracter_ascii<=47) || (caracter_ascii>=58 && caracter_ascii<=64)||(caracter_ascii>=123 && caracter_ascii<=126)){
                  mensaje= "ESPECIAL";
              }

              return mensaje;
          }
          catch (Exception e) {
              return "Ocurrió un error inesperado";
          }


      }

   /*
    * 
    * 4. Construya un algoritmo e implemente la función en Java
    * Hallar_division_exacta que pida dos números enteros,
    * calcule la división del primero sobre el segundo, y al final si la división
    * es exacta, devuelva "DIVISION EXACTA"
    * y de lo contrario devuelva "DIVISION NO EXACTA". (Exacta significa que tiene
    * cociente, pero no residuo).
    * 
    * Si alguno de los dos números que recibe es cero o negativo, devuelva
    * "NO SE ADMITE CERO O NEGATIVOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * Nota: Revise el funcionamiento del operador mod que le puede ayudar.
    * 
    * 
    * 
    */
 public static String Hallar_division_exacta (int numero_1, int numero_2){
 
      try {
        
        if(numero_1 <=0 || numero_2<= 0){
            return "no se admiten cero o negativos";
        }
       int resultado_division = numero_1/numero_2;
       int resulatado_exacto = numero_2 - (numero_1* (numero_1/numero_2));
       if (resultado_division == resulatado_exacto){
        return " división exacta ";
       } 
       else{
        return "division no excata";
       }
       

         } 
      catch (Exception e) {
         return "ocurrió un error inesperado";
       }
  }
   

   /*
    * 5. En la siguiente tabla se encuentra la información de las habitaciones de
    * una finca hotel:
    * 
    * Habitación Camas Planta    AA/VENTILADOR
    *    101         2     Primera     AA
    *    102         1     Primera     VE
    *    201         3     Segunda     AA
    *    202         2     Segunda     VE
    *    301         2     Tercera     AA
    * 
    * 
    * Construya un algoritmo e implemente la función en Java Consultar_hab que
    * reciba en un byte el número de camas
    * y en un string si desea VE o AA, y deuvelva en un texto el o los números de
    * habitación que cumplen ese requisito.
    * Si son varias habitaciones, devuelvalas separadas por el caracter |
    * (normalmente, al lado izquierdo de la tecla del 1).
    * Ejemplo: "101|301"
    * Si el número de camas no está entre 1 y 3 o el string es diferente a AA o VE,
    * devuelva "DATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

public static String Consultar_hab(byte nro_camas, String VE_AA){
        try {
            String mensaje= " ";
            final String opc_1 = "101|301", opc_2 = "202", opc_3 = "102", opc_4 = "201";
            if (nro_camas < 1 && nro_camas > 3 || VE_AA != "AA" && VE_AA != "VE") {
                return "DATOS NO VÁLIDOS";
            } else if (nro_camas==2 && VE_AA == "AA"){
                mensaje = opc_1;
            }else if (nro_camas==2 && VE_AA == "VE"){
                mensaje = opc_2;
            }else if (nro_camas==1 && VE_AA == "VE"){
                mensaje = opc_3;
            }else if (nro_camas==3 && VE_AA == "AA"){
                mensaje = opc_4;
            }
              return mensaje;  

        } catch (Exception e) {
            return "Ocurrió un error inesperado";
        }
    }

   /*
    * 
    * 6. Un restaurante vende 3 platos. Si el cliente solicita el plato 1, le dan
    * el postre gratis; si selecciona los platos
    * 1 y 2, le dan la bebida gratis y si selecciona los platos 1,2 y 3, le dan
    * postre y bebida.
    * Construya un algoritmo e implemente la función Obtener_obs en Java que reciba
    * 3 booleanos, uno para cada plato y en
    * un String devuelva el obsequio ganado en mayúscula, así: "BEBIDA", "POSTRE",
    * "BEBIDA Y POSTRE".
    * Si los 3 platos vienen en false, , devuelva "PLATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

    public static String Obtener_obs(boolean plato_1, boolean plato_2, boolean plato_3) {
    try {
        if (plato_1 == false || plato_2 == false || plato_3 == false) {
            return "platos no válidos";
        }
        
        if (plato_1 ) {
            return "POSTRE";
        } else if (plato_1 && plato_2) {
            return "BEBIDA";
        } else if (plato_1 && plato_2 && plato_3) {
            return "BEBIDA Y POSTRE";
        }
       
        return "sin obsequio";
    } catch (Exception e) {
        return "Ocurrió un error inesperado";
    }
}


   /*
    * 7. Un grupo de amigos hace un sorteo semanalmente con pelotas de ping pong,
    * para saber quién invita y a qué  la próxima salida.
    * Las opciones dependen del color que sacan en cada bola y son:
    * 
    * verde: Invita a las cervezas
    * azul: Invita a la pizza
    * rojo: Invita al postre
    * amarillo: Paga el parqueadero de todos
    * blanco o negro: Vaya y disfrute
    * Si la función recibe algo diferente a los colores dados, debe retornar
    * "Error en el color".
    * 
    * Se necesita una función en java Conocer_invitacion que reciba un string con
    * el color de la bola y retorna un
    * String con exactamente el texto de la invitación correspondiente.
    * 
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */

    public static String Conocer_invitacion (String color){

    try {
        
       String invitacion= "";
        switch (color) {
            case "azul":
                invitacion = "invita a la pizza";
              break;

            case "verde":
                invitacion = "invita a las cervezas";
             break;
             
            case "rojo":
                invitacion = "invita al postre";
            break;

            case "amarillo":
                invitacion = "paga el parqueadero";
            break;

            case "blanco":
            case "negro":
                invitacion = "vaya y disfrute";
            break;

            default:
            invitacion = "error en el color";
        
        }
        return invitacion;

    } catch (Exception e) {
       return "ocurrió un error inesperado";
    }
   }

